services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: ["/usr/local/bin/wait-for-it.sh", "postgres:5432", "--timeout=60", "--strict", "--", "/app"]

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5